### ISSUE TITLE
Flask app stopped working after updating flaskwebgui from  0.3.7. to 1.0.1.

### ISSUE THREAD

**Issue by brunocalet** [ClimenteA/flaskwebgui#102]
Working on is Pop!_OS 20.04 LTS.

I have simple Flask app that looks like this:

```main.py```:
```python
from flask import Flask
from flaskwebgui import FlaskUI

app = Flask(__name__, static_url_path='/static')

app.config.from_object(__name__)

ui = FlaskUI(
    app,
    fullscreen=True)

if __name__ == "__main__":
    ui.run()
````

When I try to run the app through the terminal like this:
```
python main.py
```

The app doesn't start in Chrome (```google-chrome-stable version (107.0.5304.110-1)```), and I also get the following error:
![image](https://user-images.githubusercontent.com/92308626/203808168-262f3e2e-2a88-4c60-a5cc-78c167ef1f5e.png)

```
Exception in thread Thread-1:
Traceback (most recent call last):
Command: /usr/bin/google-chrome --user-data-dir=/tmp/flaskwebgui --new-window --no-first-run --start-maximized --app=http://127.0.0.1:43385
  File "/home/<user>/conda/envs/<env_name>/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/<user>/conda/envs/<env_name>/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
TypeError: Flask.__call__() missing 2 required positional arguments: 'environ' and 'start_response'
Opening in existing browser session.

```

**Comment by ClimenteA** [comment]
Version 1 is not backwards compatible with the versions 0.x.x.

Checkout the docs there are some changes (no need for js script in v1). 

Or pin version in requirements if that works for you.

**Comment by Jerrykim91** [comment]
Hey Hi,  
Today, I found out about this nice package when I researching.  so I am testing it. Unfortunately  I also too. same problem. lol
I read this text all. But I don't understand. SO, You mean, we need to down grade flask version? How much? or if not How should I do ? 
I got flask == 2.1.3 and flaskwebgui  == 1.0.3  I  installed.
plz. help

**Comment by brunocalet** [comment]
Hi @Jerrykim91,
as @ClimenteA said, version 1 is not backward compatible with versions 0.x.x. If you are experiencing the same issue as I did, one fix is to downgrade flaskwebgui to version 0.3.7 (or even one of the previous versions). 

However, if you want to keep using flaskwebgui versions 1.0.1 or higher, the better fix to this issue is to change the initialization parameters of Flask app and FlaskUI to something like this:

```python
from flask import Flask
from flaskwebgui import FlaskUI

app = Flask(__name__, static_url_path='/static')

app.config.from_object(__name__)

ui = FlaskUI(
    app=app,
    server="flask",
    fullscreen=True)

if __name__ == "__main__":
    ui.run()
```

Hope that helped!

**Comment by Jerrykim91** [comment]
@brunocalet  
It works. Thank you so much~
